name: blueprint
description: Validate JSON Against Your Own Blueprint with support deep validation and null-able types with List and Map , detect the failure field
version: 0.0.1-beta
homepage: https://github.com/maxzod/blueprint
environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
